export enum UserRole {
  SUPER_ADMIN = 'SUPER_ADMIN',
  NGO_ADMIN = 'NGO_ADMIN',
  VOLUNTEER = 'VOLUNTEER',
  DONOR = 'DONOR',
  BENEFICIARY = 'BENEFICIARY',
}

export enum EquipmentStatus {
  DONATION_SUBMITTED = 'DONATION_SUBMITTED',
  REJECTED = 'REJECTED',
  VERIFIED = 'VERIFIED',
  COLLECTION_PENDING = 'COLLECTION_PENDING',
  IN_TRANSIT_TO_WAREHOUSE = 'IN_TRANSIT_TO_WAREHOUSE',
  IN_INVENTORY = 'IN_INVENTORY',
  RESERVED = 'RESERVED',
  ISSUED = 'ISSUED',
  RETURN_PENDING = 'RETURN_PENDING',
  IN_TRANSIT_TO_INSPECTION = 'IN_TRANSIT_TO_INSPECTION',
  UNDER_MAINTENANCE = 'UNDER_MAINTENANCE',
  RETIRED = 'RETIRED',
}

export enum TaskType {
  DONATION_PICKUP = 'DONATION_PICKUP',
  BENEFICIARY_DELIVERY = 'BENEFICIARY_DELIVERY',
  RETURN_PICKUP = 'RETURN_PICKUP',
}

export enum TaskStatus {
  ASSIGNED = 'ASSIGNED',
  ACCEPTED = 'ACCEPTED',
  IN_TRANSIT = 'IN_TRANSIT',
  COMPLETED = 'COMPLETED',
  FAILED = 'FAILED',
}

export enum RequestStatus {
  SUBMITTED = 'SUBMITTED',
  PENDING = 'PENDING',
  DOCS_REQUIRED = 'DOCS_REQUIRED',
  APPROVED = 'APPROVED',
  ALLOCATED = 'ALLOCATED',
  FULFILLED = 'FULFILLED',
  DELIVERED = 'DELIVERED',
  REJECTED = 'REJECTED',
  CANCELLED = 'CANCELLED',
}

export enum RequestUrgency {
  LOW = 'LOW',
  MEDIUM = 'MEDIUM',
  HIGH = 'HIGH',
  CRITICAL = 'CRITICAL',
}